minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@spartan-ng/*'
  - postcss@8.5.28
  - db0@0.4.1
  - h3@2.0.1-rc.31
  - nitro@3.0.260903-beta
  - srvx@1.0.3
  - unstorage@2.0.0-alpha.10

packages:
  - 'apps/api'

allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': false
  '@swc/core': false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: false
  prisma: false
